development:
  clients:
    default:
      database: tac_poetry
      hosts:
        - <%= "#{ENV['MONGODB_1_PORT_27017_TCP_ADDR']}:#{ENV['MONGODB_PORT_27017_TCP_PORT']}" %>
      options:
test:
  clients:
    default:
      database: tac_poetry_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

